### PR TITLE
warn when used in client components

### LINKED ISSUE #115: import server-only
We should be using https://www.npmjs.com/package/server-only to signal that our packages can't be used on the client.

> This gives a good error when using the packages on the client (which technically works for kv, blob and postgres but should never be done.

### PR DESCRIPTION
**Pull request by dferber90**
closes #115

### CODE REVIEW

**Review by cramforce — APPROVED** [review]

**Review by elliott-with-the-longest-name-on-github — COMMENTED** [review]
I'm requesting changes so that someone doesn't see "Oh, @cramforce approved this, let me merge it" -- the tests are broken because `server-only` is working _too_ well, lol

**Review by elliott-with-the-longest-name-on-github — CHANGES_REQUESTED** [review]
I'm requesting changes so that someone doesn't see "Oh, @cramforce approved this, let me merge it" -- the tests are broken because `server-only` is working _too_ well, lol

**Comment by dferber90** [comment]
- I've upgraded `@edge-runtime/jest-environment` to 2.2.0-beta.6 which includes https://github.com/vercel/edge-runtime/pull/328. This resolved the server-only issues when testing with `@edge-runtime/jest-environment`
- I've added `testEnvironmentOptions.customExportConditions` to the configs, which resolved the server-only issues when testing with node

**Comment by dferber90** [comment]
I realized we can mock `server-only` to make the unit tests pass.

But now some integration tests are failing due to `server-only`. I'm not sure whether those failures are legit or what we would expect from our packages.

```
vercel-storage-integration-test-suite:integration-test:     [Desktop Chrome] › @vercel/blob/blob.visual.test.ts:10:9 › @vercel/blob › page › serverless ────
vercel-storage-integration-test-suite:integration-test:     [Desktop Chrome] › @vercel/postgres/index.test.ts:95:11 › @vercel/postgres › pages directory › client › edge 
vercel-storage-integration-test-suite:integration-test:     [Desktop Chrome] › @vercel/postgres/index.test.ts:99:11 › @vercel/postgres › pages directory › client › node 
vercel-storage-integration-test-suite:integration-test:     [Desktop Chrome] › @vercel/postgres/index.test.ts:105:11 › @vercel/postgres › pages directory › pool › edge 
vercel-storage-integration-test-suite:integration-test:     [Desktop Chrome] › @vercel/postgres/index.test.ts:109:11 › @vercel/postgres › pages directory › pool › node 
vercel-storage-integration-test-suite:integration-test:     [Desktop Chrome] › @vercel/postgres-kysely/index.test.ts:63:11 › @vercel/postgres-kysely › pages directory › api › edge 
vercel-storage-integration-test-suite:integration-test:     [Desktop Chrome] › @vercel/postgres-kysely/index.test.ts:67:11 › @vercel/postgres-kysely › pages directory › api › node 
vercel-storage-integration-test-suite:integration-test:     [Desktop Firefox] › @vercel/postgres/index.test.ts:95:11 › @vercel/postgres › pages directory › client › edge 
vercel-storage-integration-test-suite:integration-test:     [Desktop Firefox] › @vercel/postgres/index.test.ts:99:11 › @vercel/postgres › pages directory › client › node 
vercel-storage-integration-test-suite:integration-test:     [Desktop Firefox] › @vercel/postgres/index.test.ts:105:11 › @vercel/postgres › pages directory › pool › edge 
vercel-storage-integration-test-suite:integration-test:     [Desktop Firefox] › @vercel/postgres/index.test.ts:109:11 › @vercel/postgres › pages directory › pool › node 
vercel-storage-integration-test-suite:integration-test:     [Desktop Firefox] › @vercel/postgres-kysely/index.test.ts:63:11 › @vercel/postgres-kysely › pages directory › api › edge 
vercel-storage-integration-test-suite:integration-test:     [Desktop Firefox] › @vercel/postgres-kysely/index.test.ts:67:11 › @vercel/postgres-kysely › pages directory › api › node 
vercel-storage-integration-test-suite:integration-test:     [Desktop Safari] › @vercel/postgres/index.test.ts:95:11 › @vercel/postgres › pages directory › client › edge 
vercel-storage-integration-test-suite:integration-test:     [Desktop Safari] › @vercel/postgres/index.test.ts:99:11 › @vercel/postgres › pages directory › client › node 
vercel-storage-integration-test-suite:integration-test:     [Desktop Safari] › @vercel/postgres/index.test.ts:105:11 › @vercel/postgres › pages directory › pool › edge 
vercel-storage-integration-test-suite:integration-test:     [Desktop Safari] › @vercel/postgres/index.test.ts:109:11 › @vercel/postgres › pages directory › pool › node 
vercel-storage-integration-test-suite:integration-test:     [Desktop Safari] › @vercel/postgres-kysely/index.test.ts:63:11 › @vercel/postgres-kysely › pages directory › api › edge 
vercel-storage-integration-test-suite:integration-test:     [Desktop Safari] › @vercel/postgres-kysely/index.test.ts:67:11 › @vercel/postgres-kysely › pages directory › api › node 
```

It seems like `server-only` is throwing incorrectly in those cases as they seem to be legitimate uses within `pages/api` <picture data-single-emoji=":thonk:" title=":thonk:">:thonk:</picture>

**Comment by dferber90** [comment]
Closing as this didn't get any response from the storage team. Can be reopened later when it becomes relevant again.

**Pull request closed without merging**
