### PR TITLE
skip client upload authentication locally

### PR DESCRIPTION
**Pull request by correttojs**
skip client upload authentication locally

### CODE REVIEW

**Comment by vvo** [comment]
Should we update the other places too?

CleanShot 2023-07-21 at 9 14 44

**Comment by vvo** [comment]
cc @correttojs

**Comment by correttojs** [comment]
> cc @correttojs

forgot about it, will update the PR

**Comment by correttojs** [comment]
@vvo the `validateUploadToken` is the only place we are validating the`BLOB_UPLOAD_SECRET`

**Review by vvo — APPROVED** [review]

**Comment by vvo** [comment]
> @vvo the `validateUploadToken` is the only place we are validating the`BLOB_UPLOAD_SECRET`

Right 🤣

**Pull request merged**
