### PR TITLE
fix(deps): Change `jest-environment-jsdom` to a devDependency.

### LINKED ISSUE #518: `@vercel/blob` includes `jest-environment-jsdom` as a normal dependency
I might be missing something here, but `@vercel/blob` includes `jest-environment-jsdom` as a normal dependency when it most likely should be a `devDependency`.

### PR DESCRIPTION
**Pull request by filiphsps**
This resolves #518.

### CODE REVIEW

**Review by vvo — APPROVED** [review]

**Comment by vvo** [comment]
Perfect PR, thanks!

**Comment by filiphsps** [comment]
> Perfect PR, thanks!

Thanks, yeah I mean it's better to spend less than 5 minutes learning how the repo is setup and what form of commit message y'all prefer than to go back and forth in the comments :)

**Comment by filiphsps** [comment]
```
  ../../packages/blob/dist/client.js
  A Node.js module is loaded ('crypto' at line 3) which is not supported in the Edge Runtime.
  Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
  
  Import trace for requested module:
  ../../packages/blob/dist/client.js
  ./src/app/vercel/blob/handle-blob-upload.ts
  
     Linting and checking validity of types ...
     Collecting page data ...
  i [VercelPostgresError]: VercelPostgresError - 'missing_connection_string': You did not supply a 'connectionString' and no 'POSTGRES_URL' env var was found.
```

```
Error: ENOENT: no such file or directory, open '/home/runner/work/storage/storage/packages/edge-config/tsup.config.bundled_ayuowxvut8f.mjs'
      at Object.openSync (node:fs:596:3)
      at Object.readFileSync (node:fs:464:35)
      at CLIEngine.executeOnFiles (/home/runner/work/storage/storage/node_modules/.pnpm/eslint@8.52.0/node_modules/eslint/lib/cli-engine/cli-engine.js:835:26)
      at ESLint.lintFiles (/home/runner/work/storage/storage/node_modules/.pnpm/eslint@8.52.0/node_modules/eslint/lib/eslint/eslint.js:551:23)
      at Object.execute (/home/runner/work/storage/storage/node_modules/.pnpm/eslint@8.52.0/node_modules/eslint/lib/cli.js:402:36)
      at async main (/home/runner/work/storage/storage/node_modules/.pnpm/eslint@8.52.0/node_modules/eslint/bin/eslint.js:146:24)
   ELIFECYCLE  Command failed with exit code 2.
```

The failing tests seems to be unrelated to this PR; but I'd advice taking a manual look before merging as to not break anything! 👍

**Comment by vvo** [comment]
@dferber90 Hi there, we're getting strange tsup errors frmo edge-config packages in tests, any idea what this is?

**Comment by vvo** [comment]
Sorry I can't make this PR pass our tests for some authorization issue, will open another one with same commits

**Comment by dferber90** [comment]
@vvo  not sure, first time I’m seeing that

**Pull request closed without merging**
